version: '3.8'

services:
  sms-ui:
    build:
      context: .
      dockerfile: Dockerfile.dokploy
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: https://api.example.com
      NEXTAUTH_URL: https://app.example.com
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      # Remove NODE_TLS_REJECT_UNAUTHORIZED in prod; use proper HTTPS
    expose:
      - '3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`app.example.com`)'
      - 'traefik.http.routers.app.entrypoints=websecure'
      - 'traefik.http.routers.app.tls.certresolver=letsencrypt'
      - 'traefik.http.services.app.loadbalancer.server.port=3000'
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3000/ || exit 1']
      interval: 30s
      timeout: 5s
      retries: 5
